### ISSUE TITLE
dl_lib.h is missing

### ISSUE THREAD

**Issue by consolacion** [Hermann-SW/Raspberry_v1_camera_global_external_shutter#1]
dl_lib.h  seems missing, or is not included with the latest core.
comment out the #include line and still compiles fine

**Comment by Hermann-SW** [comment]
Thanks, commited and pushed:
https://github.com/Hermann-SW/Raspberry_v1_camera_global_external_shutter/commit/79e2ede15fc0859b573597e40130928775e68c9
