### ISSUE TITLE
Mult-camera sync possible?

### ISSUE THREAD

**Issue by ibprojects** [Hermann-SW/Raspberry_v1_camera_global_external_shutter#2]
Hi Hermann,

Is it possible to sync multiple cameras using FREX?

I'm trying to use inexpensive cameras to create this: 

![image](https://user-images.githubusercontent.com/65034483/175368875-f01cd782-f415-44ad-a0c4-ba512c3906f9.png)

If you know a good path for this with ESP32s or RPis I would really enjoy speaking with you. Happy to pay for your time.

Thank you!
Ian ianbroyles at gmail

(Please delete this if this is not the right place for this)

**Comment by Hermann-SW** [comment]
The introduction link to (v1 camera) FREX mode
[https://cdn.sparkfun.com/datasheets/Dev/RaspberryPi/ov5647_full.pdf#page=43](https://cdn.sparkfun.com/datasheets/Dev/RaspberryPi/ov5647_full.pdf#page=43)
details that FREX does start integration of all rows at same time, contrary to normal rolling shutter operation where each row starts integration at a slightly different time. I am not aware how to sync multiple cameras with FREX.

I would expect that ESP32s are too slow for camera processing.
Cheapest option would be a Pi0[W], or performance wise preferable Pi0W2.

You can only connect 1 CSI camera per (non-CM) Pi.
While you can connect several USB cameras, I don't know how to sync.

Best Raspberry camera wrt sync (but probably to expensive) is HQ camera:
[https://forums.raspberrypi.com/viewtopic.php?t=281913](https://forums.raspberrypi.com/viewtopic.php?t=281913)

Cheapest solution would be 4 Pi0s with one  3$ v1 5MP camera for each of them.
Syncing can be done with code from MIT peoply project synchronising 16 v1 cameras:
[https://forums.raspberrypi.com/viewtopic.php?f=43&t=240442](https://forums.raspberrypi.com/viewtopic.php?f=43&t=240442)
<img src="https://media.giphy.com/media/QZn7DqKHY478NnbGjp/giphy.gif">

**Comment by ibprojects** [comment]
That's a great project! 

The setup is similar to what I had in mind with ESP32s with cameras:

4 ESP32-camera-units mounted behind a physical shutter in darkness. 

1) Open shutters on cameras via long exposure or FREX mode
2) Open and close the physical shutter (and pop a flash if needed)
3) Write out image to SD card and send to host computer / phone (via Wifi)
4) Use host computer / phone (I am an iOS developer so I can make an app) to sew images together in GIF or movie. 

My other approach was to use FPGAs and get the cameras all in sync similar to this:
(I need to gain more experience in this area)

https://www.xilinx.com/video/corporate/real-time-collaboration-panoramic-video-conferencing.html

Thank you for your reply, it is very helpful. I wish there was an easier way to get 4 inexpensive cameras completely in sync :)
