### ISSUE TITLE
Raspiraw

### ISSUE THREAD

**Issue by AlzuhiriMohand** [Hermann-SW/Raspberry_v1_camera_global_external_shutter#3]
Is it possible to acquire raw data with global shutter? I noticed that you mentioned raspiraw_ges but I cannot find in the tools.

**Comment by Hermann-SW** [comment]
You can find all tools in "tools" directory, raspivid_ges did use raspividyuv, but capturing raw is possible eg. with using "raspivid" with "--raw" option

**Comment by AlzuhiriMohand** [comment]
Thank you for the quick reply, I need raspiraw because I need 10-bit Bayer data, at 1664*1232 at 15 fps, and a preview window (to my knowledge, only raspiraw can provide that). The only problem here is that I am losing the hardware camera synch pulses (https://forums.raspberrypi.com/viewtopic.php?t=190314). Is losing the pulses normal or I am doing something wrong? Any idea about a workaround?

**Comment by Hermann-SW** [comment]
Hardware sync pulses are generated by raspivid, and are missing in raspiraw.

But you can add them in this line:
https://github.com/raspberrypi/raspiraw/blob/master/raspiraw.c#L700

**Comment by AlzuhiriMohand** [comment]
Thank you for this nice solution. It works with a small modification. It is better to add the flash signal before line 578 if we want a Bayer data output.

https://github.com/raspberrypi/raspiraw/blob/master/raspiraw.c#L578 

We also need to run an If statement to avoid the extra call of the buffer (only trigger when (buffer->flags)==0004)

if((buffer->flags)<10){
gpioWaveTxSend(wave_id, PI_WAVE_MODE_ONE_SHOT);
}
