### ISSUE TITLE
Qr code reader

### ISSUE THREAD

**Issue by tamano123** [Hermann-SW/Raspberry_v1_camera_global_external_shutter#5]
Hello,

I need to make a qrcode scanner of moving qrcodes with external trigger (exactly like in this video https://www.youtube.com/watch?v=f_saNQQACOo).

1. Is it possible to do it with your module ?
2. i have a python script that gives the instruction to the camera to capture the image, is it possible to control your module from a python script ?

Thank you

**Comment by Hermann-SW** [comment]
> Is it possible to do it with your module ?
>
No external trigger for Raspberry v1 camera (clone) with ov5647 sensor.
But Arducam sells an ov5647 with external trigger.
But you should use a Global Shutter camera for this kind of application (either from Arducam, or new Raspberry Pi GS camera).
